import { Router, Request, Response } from 'express';
import { SQLWrapper, AnyColumn, desc, asc, eq, and, sql} from 'drizzle-orm';
import { toSnakeCase } from 'drizzle-orm/casing';
// import { eq, and, asc, desc } from 'drizzle-orm/expressions';
import { PgTable } from 'drizzle-orm/pg-core';
// import { authCheckJwt, authRequiredPermissions, getOrgIdFromJwt } from './auth';
import { z } from 'zod';
import { SQL } from 'drizzle-orm';
import { count } from 'drizzle-orm';
// escapeString import removed — it is designed for SQL string values, not
// identifiers. Column-name safety is enforced by SAFE_IDENTIFIER_RX below.
// import { getUserRoles } from '../auth0/client';
import { asyncHandler } from '../middleware/errorHandler';

/**
 * Regex that matches only characters safe for a SQL column identifier.
 * Permits word characters (letters, digits, underscore) which covers all
 * valid Postgres column names generated by Drizzle's toSnakeCase().
 */
const SAFE_IDENTIFIER_RX = /^\w+$/;

/**
 * Exhaustive whitelist of comparison operators permitted in filter values.
 * Only these exact strings may be passed to sql.raw() for operator
 * interpolation; everything else is silently skipped.
 */
const ALLOWED_OPERATORS = ['>=', '<=', '<>', '!=', '>', '<'] as const;

/**
 * @param req The current Express request.
 * @param queryParams Parsed pagination, sorting, and filter parameters.
 * @param table The optional Drizzle table used to validate filter keys.
 * @return A SQL `where` clause built from query filters, or `undefined` when no filters are present.
 * @details Converts query-string filters into a Drizzle SQL fragment. The function
 * supports equality filters by default, handles explicit `null` values, and also
 * accepts inline comparison operators such as `>=`, `<=`, `!=`, `>`, and `<`.
 *
 * Security: When a `table` is provided, filter keys are validated against the
 * table's own properties
 * (preventing prototype-pollution attacks via `toString`, `__proto__`, etc.)
 * and are checked against a safe-identifier regex before being interpolated
 * with `sql.raw()`. Comparison operators are matched against an explicit
 * whitelist.
 */
function defaultWhereClause<T extends PgTable<any>>(
	req: Request,
	queryParams: QueryParams,
	table?: T
): SQL | undefined {
	const filters = queryParams.filters;
	if (!filters || Object.keys(filters).length === 0) {
		// no filters -> no "where" clause
		return undefined;
	}

	const conditions: SQL[] = [];

	for (const key of Object.keys(filters)) {
		let value = filters[key];

		// Use hasOwnProperty instead of `in` to prevent prototype pollution.
		// The `in` operator traverses the prototype chain, so keys like
		// "toString", "constructor", or "__proto__" would pass through.
		if (table && !Object.prototype.hasOwnProperty.call(table, key)) {
			continue;
		}

		// Validate that the snake_case column name contains only safe
		// identifier characters (word chars: [a-zA-Z0-9_]) before passing
		// to sql.raw(). This rejects any key that could break out of the
		// double-quoted identifier context.
		const snakeKey = toSnakeCase(key);
		if (!SAFE_IDENTIFIER_RX.test(snakeKey)) {
			continue;
		}

		const column = sql.raw(`"${snakeKey}"`);

		if (value === null || value === 'null') {
			// NULL handling
			conditions.push(sql`${column} IS NULL`);
			continue;
		}

		// detect operator inside value (no naming convention needed)
		if (typeof value === 'string') {
			const trimmed = value.trim();
			const opMatch = trimmed.match(/^(>=|<=|<>|!=|>|<)\s*(.+)$/);
			if (opMatch) {
				const operator = opMatch[1];

				// Only allow whitelisted operators through sql.raw()
				if (!(ALLOWED_OPERATORS as readonly string[]).includes(operator)) {
					continue;
				}

				const operandRaw = opMatch[2];
				const operand = parseValue(operandRaw);
				conditions.push(sql`${column} ${sql.raw(operator)} ${operand}`);
				continue;
			}
		}

		// default equality
		conditions.push(sql`${column} = ${value}`);
	}

	if (conditions.length === 0)
		return undefined;
	if (conditions.length === 1)
		return conditions[0];

	return sql.join(conditions, sql` AND `);
}

/**
 * @param v The raw filter operand read from the query string.
 * @return A normalized primitive value, converted to boolean or number when possible.
 * @details Used by filter parsing to interpret string operands like `true`, `false`,
 * or numeric values before they are inserted into a SQL comparison expression.
 */
function parseValue(v: any) {
  const s = String(v).trim();

  if (s.toLowerCase() === 'true') return true;
  if (s.toLowerCase() === 'false') return false;
  
  const n = Number(s);
  if (!isNaN(n)) return n;

  return v;
}

// Types for query parameters
export interface QueryParams {
    page: number;
    limit: number;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
    filters?: Record<string, any>;
}

interface PaginatedResponse<T> {
    items: T[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
}

interface TableWithId {
    id: AnyColumn;
}

export type ValidationError = {
    code?: string,
    expected?: string,
    received?: string,
    path?: Array<string>
    message: string
}

export type ValidationResult = {
    success: boolean
    error?: {
        errors: Array<ValidationError>
    }
    data?: any
}

export type InsertValidator = {
    schema?: z.ZodSchema,
    custom?: (body:any) => Promise<ValidationResult>,
}

interface CrudRouterOptions<T extends PgTable<any> & TableWithId> {
    table: T;
    typeName: string;
    buildWhereClause?: (req: Request, queryParams: QueryParams) => SQL | undefined;
    validateBody?: InsertValidator;
    transformResponse?: (item: any) => any;
    transformRequest?: (req: Request) => any;
}

function getSingleQueryParam(value: unknown): string | undefined {
    if (Array.isArray(value)) {
        return typeof value[0] === 'string' ? value[0] : undefined;
    }

    return typeof value === 'string' ? value : undefined;
}

function parsePositiveIntegerQueryParam(value: unknown, fallback: number): number {
    const rawValue = getSingleQueryParam(value);

    if (rawValue === undefined) {
        return fallback;
    }

    const normalizedValue = rawValue.trim();

    if (!/^\d+$/.test(normalizedValue)) {
        return fallback;
    }

    const parsedValue = Number.parseInt(normalizedValue, 10);
    return Number.isSafeInteger(parsedValue) ? parsedValue : fallback;
}

/**
 * @param req The current Express request.
 * @return A normalized `QueryParams` object with parsed paging, sorting, and filter values.
 * @details Reads query-string parameters from the request and applies the current
 * defaults and bounds for `page`, `limit`, and `sortOrder`, leaving all other
 * query-string keys available as filter values.
 */
export function parseQueryParams(req: Request): QueryParams {
    const {
        page,
        limit,
        sortBy,
        sortOrder = 'asc',
        ...filters
    } = req.query;

    return {
        page: Math.max(1, parsePositiveIntegerQueryParam(page, 1)),
        limit: Math.min(100, Math.max(1, parsePositiveIntegerQueryParam(limit, 100))),
        sortBy: getSingleQueryParam(sortBy),
        sortOrder: getSingleQueryParam(sortOrder)?.toLowerCase() === 'desc' ? 'desc' : 'asc',
        filters
    };
}

/**
 * @param table The Drizzle table being queried.
 * @param sortBy The optional property name to sort by.
 * @param sortOrder The requested sort direction, defaulting to ascending.
 * @return A Drizzle order-by wrapper when the field exists on the table, otherwise `null`.
 * @details Validates the requested sort field against the table definition and
 * constructs either an ascending or descending order clause for list queries.
 */
function buildOrderClause<T extends PgTable<any>>(
    table: T,
    sortBy?: string,
    sortOrder: 'asc' | 'desc' = 'asc'
): SQLWrapper | null {
    if (sortBy && Object.prototype.hasOwnProperty.call(table, sortBy)) {
        const col = table[sortBy as keyof T] as AnyColumn;
        return sortOrder === 'desc' ? desc(col) : asc(col);
    }
    return null;
}

/**
 * @param user The user record returned from the database.
 * @return The original user or a user object extended with a `roles` array.
 * @details This helper is currently used only for the special `users` type path.
 * The role lookup is stubbed out in the current code and returns an empty roles array.
 */
async function enhanceUserData(user: any) {
    console.log('user', user);
    if (!user?.email) return user;
    const roles:Array<string> = []; //await getUserRoles(user.email);
    return { ...user, roles };
}

/**
 * @param options The CRUD router configuration, including table metadata, validation hooks,
 * and optional request/response transformations.
 * @return An Express router exposing list, get, create, update, and delete routes for the table.
 * @details Builds the shared CRUD router used by multiple APAP resources. The current
 * implementation applies optional request validation, pagination, filtering, sorting,
 * record transformation hooks, and basic database-backed handlers for standard CRUD operations.
 */
export function buildCrudRouter<T extends PgTable<any> & TableWithId>({
    table,
    typeName,
    buildWhereClause,
    validateBody,
    transformResponse,
    transformRequest
}: CrudRouterOptions<T>): Router {
    const router = Router();

    // router.use(authCheckJwt);

    // Secure middleware to check for org_id
    router.use(async (req: Request, res: Response, next) => {
        // if (!req.auth?.payload) {
        //     return res.status(401).json({ error: 'Unauthorized - Missing or invalid JWT' });
        // }

        // const orgId = await getOrgIdFromJwt(req);
        // if (!orgId) {
        //     return res.status(403).json({ 
        //         error: 'Forbidden - Organization ID is required',
        //         details: 'Valid organization membership is required to access this resource'
        //     });
        // }
        
        res.locals.orgId = undefined; //orgId;
        next();
    });

    // Reject non-strict-numeric :id early for integer-keyed tables (#162). parseInt('1abc')
    // returns 1, so without this guard PUT /agreements/1abc with a valid body silently updates
    // row 1, and DELETE /templates/1abc silently deletes row 1. UUID-keyed tables keep the
    // existing pass-through; the DB layer surfaces malformed UUIDs.
    router.param('id', (req: Request, res: Response, next, rawId: string) => {
        if (table.id.columnType === 'PgUUID') {
            return next();
        }
        if (!/^\d+$/.test(rawId)) {
            return res.status(404).json({ error: 'Not found' });
        }
        next();
    });

    // GET with pagination, sorting, and filtering
    router.get('/',
        // authRequiredPermissions('read:' + typeName),
        asyncHandler(async (req: Request, res: Response) => {
                const queryParams = parseQueryParams(req);
                const { page, limit, sortBy, sortOrder } = queryParams;
                const whereClause = buildWhereClause ? buildWhereClause(req, queryParams) : 
                    defaultWhereClause(req, queryParams, table);
                const orderClause = buildOrderClause(table, sortBy, sortOrder);

                // Log the generated SQL
                let logQuery = res.locals.db
                    .select()
                    .from(table)
                    .where(whereClause)
                    .limit(limit)
                    .offset((page - 1) * limit);

                if (orderClause !== null) {
                    logQuery = logQuery.orderBy(orderClause as SQL<unknown>);
                }



                // Get total count for pagination
                const [{ count: total }] = await res.locals.db
                    .select({ count: count() })
                    .from(table)
                    .where(whereClause);

                // Get paginated results
                let query = res.locals.db
                    .select()
                    .from(table)
                    .where(whereClause)
                    .limit(limit)
                    .offset((page - 1) * limit);

                if (orderClause !== null) {
                    query = query.orderBy(orderClause as SQL<unknown>);
                }

                const items = await query;

                const response: PaginatedResponse<any> = {
                    items,
                    total: total,
                    page,
                    limit,
                    totalPages: Math.ceil(total / limit)
                };

                // Modify the GET responses to include roles
                if (typeName === 'users') {
                    response.items = await Promise.all(items.map(enhanceUserData));
                } else {
                    response.items = items;
                }

                if (transformResponse) {
                    response.items = response.items.map(transformResponse);
                }

                res.json(response);
        }));

    // POST new item
    router.post('/',
        // authRequiredPermissions('write:' + typeName),
        asyncHandler(async (req: Request, res: Response) => {
                if (!req.body) {
                    return res.status(400).json({ error: 'Missing request body' });
                }

                // Add organization to the request body
                req.body = {
                    ...req.body,
                    organization: res.locals.orgId
                };

                // Validate body if schema provided
                if (validateBody?.schema) {
                    const result = validateBody.schema.safeParse(req.body);
                    if (!result.success) {
                        return res.status(400).json({ 
                            error: 'Invalid request body',
                            details: result.error.errors 
                        });
                    }
                    req.body = result.data;  // Use validated data
                    if(validateBody.custom) {
                        const result = await validateBody.custom(req.body);
                        if (!result.success) {
                            return res.status(400).json({ 
                                error: 'Invalid request body',
                                details: result.error.errors 
                            });
                        }
                        req.body = result.data;  // Use validated data        
                    }
                }

                if (transformRequest) {
                    req.body = transformRequest(req);
                }

                let inserted;
                try {
                    inserted = await res.locals.db
                        .insert(table)
                        .values(req.body)
                        .returning();
                } catch (error: any) {
                    if (error?.code === '23505') {
                        const pgError = new Error('Unique constraint violation') as any;
                        pgError.code = '23505';
                        pgError.typeName = typeName;
                        throw pgError;
                    }
                    throw error;
                }

                if (transformResponse) {
                    inserted[0] = transformResponse(inserted[0]);
                }

                res.json(inserted[0]);
        }));

    // GET single item
    router.get('/:id',
        // authRequiredPermissions('read:' + typeName),
        asyncHandler(async (req: Request, res: Response) => {
                const queryParams = parseQueryParams(req);
                const whereConditions = [
                    // Check if table has UUID primary key
                    table.id.columnType === 'PgUUID' ? 
                        eq(table.id, req.params.id) :
                        eq(table.id, parseInt(req.params.id))
                ].filter(Boolean);

                const result = await res.locals.db
                    .select()
                    .from(table)
                    .where(and(...whereConditions))
                    .limit(1);

                if (!result.length) {
                    return res.status(404).json({ error: 'Not found' });
                }

                // Enhance single user response with roles
                if (typeName === 'users') {
                    const enhancedUser = await enhanceUserData(result[0]);
                    if (transformResponse) {
                        result[0] = transformResponse(enhancedUser);
                    }
                    return res.json(result[0]);
                }

                if (transformResponse) {
                    result[0] = transformResponse(result[0]);
                }

                res.json(result[0]);
        }));

    // PUT update item
    router.put('/:id',
        // authRequiredPermissions('write:' + typeName),
        asyncHandler(async (req: Request, res: Response) => {
                // Add organization to the request body
                if (!req.body || Object.keys(req.body).length === 0) {
                    return res.status(400).json({
                        error: 'Invalid request body',
                        details: [{ message: 'Request body cannot be empty' }]
                    });
                }

                req.body = {
                    ...req.body,
                    organization: res.locals.orgId
                };

                // Run schema validation independently
                if (validateBody?.schema) {
                    const result = validateBody.schema.safeParse(req.body);
                    if (!result.success) {
                        return res.status(400).json({
                            error: 'Invalid request body',
                            details: result.error.errors
                        });
                    }
                    req.body = result.data;
                }

                // Run custom validation independently (not nested inside schema check)
                if (validateBody?.custom) {
                    const customResult = await validateBody.custom(req.body);
                    if (!customResult.success) {
                        return res.status(400).json({
                            error: 'Invalid request body',
                            details: customResult.error.errors
                        });
                    }
                    req.body = customResult.data;
                }

                if (transformRequest) {
                    req.body = transformRequest(req);
                }

                const queryParams = parseQueryParams(req);
                const whereConditions = [
                    table.id.columnType === 'PgUUID' ? 
                        eq(table.id, req.params.id) :
                        eq(table.id, parseInt(req.params.id))
                ].filter(Boolean);

                let updated;
                try {
                    updated = await res.locals.db
                        .update(table)
                        .set(req.body)
                        .where(and(...whereConditions))
                        .returning();
                } catch (error: any) {
                    if (error?.code === '23505') {
                        const pgError = new Error('Unique constraint violation') as any;
                        pgError.code = '23505';
                        pgError.typeName = typeName;
                        throw pgError;
                    }
                    throw error;
                }

                if (!updated.length) {
                    return res.status(404).json({ error: 'Not found' });
                }

                if (transformResponse) {
                    updated[0] = transformResponse(updated[0]);
                }

                res.json(updated[0]);
        }));

    // DELETE item
    router.delete('/:id',
        // authRequiredPermissions('write:' + typeName),
        asyncHandler(async (req: Request, res: Response) => {
                const queryParams = parseQueryParams(req);
                const whereConditions = [
                    table.id.columnType === 'PgUUID' ? 
                        eq(table.id, req.params.id) :
                        eq(table.id, parseInt(req.params.id))
                ].filter(Boolean);

                const result = await res.locals.db
                    .delete(table)
                    .where(and(...whereConditions))
                    .returning();

                if (!result.length) {
                    return res.status(404).json({ 
                        error: 'Not found',
                        details: [{ message: `Resource with id ${req.params.id} does not exist` }]
                    });
                }
                res.json({ status: 'deleted' });
        }));

    return router;
}
