name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t apap ./server
        docker tag apap accordproject/apap:latest
        docker push accordproject/apap:latest

    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@v1.1.1
      with:
        # AWS access key id
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS secret access key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Where EC2 instance is
        aws-region: ${{ secrets.AWS_REGION }}
        # AWS EC2 Instance id or ids
        instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
        # Command execution location
        # !!! The line below may vary depending on where your docker-compose file is located.
        working-directory: /home/ubuntu
        # Bash commands you want to execute
        command: |
          echo "${{ secrets.HTPASSWD_CONTENT }}" > ./htpasswd
          sudo docker-compose -f ./compose-aws.yaml stop  
          sudo docker-compose -f ./compose-aws.yaml rm -f
          sudo docker-compose -f ./compose-aws.yaml pull
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} sudo docker-compose -f ./compose-aws.yaml up -d
          sudo docker image prune -af